### PR TITLE
Add [M+H-2(H2O)]+ adduct

### PR DESCRIPTION
**Pull request by jorainer**
This PR adds the `[M+H-2(H2O)]+` adduct that we also see sometimes in our HILIC data. Question is however if it is written/defined in the proper way - @michaelwitting ?

### CODE REVIEW

**Comment by michaelwitting** [comment]
No, there is no proper way at the moment. I prefer to have it [M+H-H4O2]+. Discussing some "more common adduct names" could be something for the hackathon.

**Review by michaelwitting — CHANGES_REQUESTED** [review]
I prefer to have formulas summed up, so 2(H2O) should be H4O2.

**Comment by jorainer** [comment]
Yes, that makes sense. I will update.

**Comment by jorainer** [comment]
UPDATE: I also added a `[M-CHO2]+` adduct - guess the name should be correct - we also called that `[M+H-HCOOH]+` but I guess the `[M-CHO2]+` might fit better the sum formulas...

**Comment by michaelwitting** [comment]
Sorry, I think I should have been more clear on how to use the sum formula. I always include the ion that was used for ionization and then the part that is lost or added as sum formula. So `[M+H-HCOOH]+` should be better `[M+H-CH2O2]+`. I think we should discuss this in more detail maybe during a call?

**Comment by jorainer** [comment]
Excellent! That is perfectly clear (and makes a lot of sense!). I will update

**Comment by jorainer** [comment]
>  I always include the ion that was used for ionization and then the part that is lost or added as sum formula.

maybe that could be something that you could add to the vignette? it would users to understand how the adducts are named in this package

**Comment by jorainer** [comment]
and I've updated the adduct name

**Comment by michaelwitting** [comment]
> > I always include the ion that was used for ionization and then the part that is lost or added as sum formula.
> 
> maybe that could be something that you could add to the vignette? it would users to understand how the adducts are named in this package

Yes, I can do that. Maybe we can have the adduct translation also in  (#35). All togheter in an "adduct vignette"

**Review by michaelwitting — APPROVED** [review]
Now the new adduct definitions are fine.

**Pull request merged**
