### PR TITLE
Update chemFormula.R, fixing #51

### PR DESCRIPTION
**Pull request by meowcat**

### CODE REVIEW

**Review by sgibb — APPROVED** [review]
Thanks for this fix!

**Comment by jorainer** [comment]
Thanks Michele @meowcat !

**Review by jorainer — CHANGES_REQUESTED** [review]
Minor changes:

- Please increase version in `DESCRIPTION`.
- Please add yourself as contributor to DESCRIPTION.
- Please add an entry into NEWS.md describing your fix (referrencing also the issue).

**Review by jorainer — APPROVED** [review]
Thanks! I will bump the version, add the NEWS and push to BioC

**Pull request merged**
